### ISSUE TITLE
4 Parameter Learning. 4.1 Maximum Likelihood Parameter Learning

### ISSUE THREAD

**Issue by cristhianpoveda** [algorithmsbooks/decisionmaking#100]
When explaining the second challenge on page 72 it says: "The other challenge is performing the maximization in equation (4.3)", but shouldn't the referred equation be 4.2 instead of 4.3? Because it would make sense that eq. 4.2 is the one that is difficult to maximize, and then eq. 4.3 is presented as an approach for solving the issue.

**Comment by mykelk** [comment]
Actually, it should be (4.1) instead of (4.3). We will fix this and post a refreshed PDF at the end of December. Thanks!

**Comment by cristhianpoveda** [comment]
Thank you.
By the way, awesome book!
