### ISSUE TITLE
Norm in SetCategorical

### ISSUE THREAD

**Issue by aidmandorky** [algorithmsbooks/decisionmaking#101]
Hello, 

Many thanks for such a wonderful book! 

I had a minor issue/question with the implementation of the `SetCategorical` structure given in the appendix G.5. 
```
ℓ₁ = norm(weights,1)
if ℓ₁ < 1e-6 || isinf(ℓ₁)
return SetCategorical(elements)
```
If I understand it correctly, this is a check to verify if the weights are degenerate or not (as described in page 179 of https://www.irisa.fr/aspi/legland/ensta/ref/arulampalam02a.pdf). If this is indeed the case, then shouldn't we use `1 / norm(weights,2)` for the value of `ℓ₁` instead as is recommended in the paper? 

In the current form, if we take weights to be the observation probabilities (which is what we do in Algorithm 19.6): 
```
function update(b::ParticleFilter, 𝒫, a, o)
T, O = 𝒫.T, 𝒫.O
states = [rand(T(s, a)) for s in b.states]
weights = [O(a, s′, o) for s′ in states]
D = SetCategorical(states, weights)
return ParticleFilter(rand(D, length(states)))
``` 
then won't the value of `ℓ₁` just be `1.`?

**Comment by tawheeler** [comment]
Thank you for filing an issue! I will take a closer look tomorrow.
So far I have only taken a quick glance at the question, and yes, `ℓ₁` will almost always be 1. The if statement you are looking at guards against the case, for example, if you end up in an invalid state and all observations are zero, such that `ℓ₁` is 0. Or, similarly, it guards against Inf values. This is normally not necessary, as these are degenerate cases.

We do use `1/norm(weights,2)` in the `normalize` step that happens right after the if statement in question.

**Comment by tawheeler** [comment]
> If I understand it correctly, this is a check to verify if the weights are degenerate or not.

Yes, exactly. The common issues here are when all values are extremely close to zero, which can happen for invalid state transitions, or (when writing a textbook), trying to plot over all possible observations, even when some are invalid. In such cases something like  `O(a, s′, o) for s′ in states` will be all zeros. 

We could set the result to a uniform distribution (`1/length(weights)`), throw an exception, or as we do here, simply return all zeros. The "right thing" for these degenerate cases typically depends on the context in which the code is used and the preferences of the user.

> If we take weights to be the observation probabilities then won't the value of ℓ₁ just be 1.?

The weights will typically not sum to `1.`. The observation function has no notion of how many samples we have. Suppose we have a simple problem were `O(a, s', o)` outputs 0.5 for all `a`, `s'`, and `o`. If we have two samples we'd get `weights= [0.5, 0.5]` and `ℓ₁ = 1`. If we had 5 samples we'd have `weights = [0.5, 0.5, 0.5, 0.5, 0.5]` and `ℓ₁ = 2.5`. Normalizing is needed in most cases.

I hope that makes sense!

**Comment by aidmandorky** [comment]
That does indeed make sense, thank you very much for your prompt response!
