### ISSUE TITLE
Chapter 10, Eq (10.13)

### ISSUE THREAD

**Issue by gncs** [algorithmsbooks/decisionmaking#103]
![image](https://user-images.githubusercontent.com/1926852/226112037-5e49d663-a7c8-4201-8814-c387ebdae276.png)

For the (admittedly special) case of $m=1$, the (only) weight $w^{(0)} = 0$. Is that the intended behavior? Thank you very much for clarifying.

**Comment by tawheeler** [comment]
You are correct that if you used m=1 that you would get a single zero weight. In this case you would want to choose a different weighting scheme.

**Comment by mykelk** [comment]
Should we add before the footnote: `, assuming $m>1$, is`?

**Comment by tawheeler** [comment]
I'm worried that adding that would leave the reader wondering why one would consider using $m=1$. We're not aiming for readers to associate evolution strategies with drawing a single sample and then updating their distribution with that single sample. As far as Eq 10.13 goes, we don't stipulate that this weighting scheme is the only one used, but merely a common recommended one for most applications, which it is.

Btw, thank you Gregor for pointing this out. Oftentimes we should include pointers like this for common gotchas. Its just that in this case it isn't a gotcha that one would run into in practical use, and if one does run into it, the way to overcome it is immediately apparent.
