### ISSUE TITLE
Wording in Chapter 10.6: Mirror Sampling

### ISSUE THREAD

**Issue by gncs** [algorithmsbooks/decisionmaking#104]
I am unsure if this is the correct place to ask this question, but I was wondering if the wording of the following could be improved.
![image](https://user-images.githubusercontent.com/1926852/226112900-baf3d15a-4da0-495c-b627-697c724f4bb1.png)
Algorithm 10.6 suggests that the sample is undergoing a point reflection (or inversion) around the origin. By contrast, to me, mirroring is a [reflection](https://en.wikipedia.org/wiki/Reflection_(linear_algebra)) in a hyperplane, which is different.

Do you agree? Please let me know what your thoughts are.

**Comment by tawheeler** [comment]
I think you're trying to get at the difference between these two:
![image](https://user-images.githubusercontent.com/3334079/226144707-451f6009-c5a1-48ff-af7a-cf21ae24a38d.png)

Here we are using the language used in the literature and we repeat the mirrored part (highlighted) to explain the nomenclature. In this case there is no plane to reflect off of, so point reflection should be reliably inferred.

**Comment by gncs** [comment]
Thank you for clarifying, @tawheeler. I prefer the term "point reflection," but I also understand that you try to stick to the language used in the literature, even if it is confusing (me).
