### ISSUE TITLE
Typo in Algorithm 21.9

### ISSUE THREAD

**Issue by Tom-CCS** [algorithmsbooks/decisionmaking#109]
See https://edstem.org/us/courses/47943/discussion/3918713?answer=9064437

**Comment by mykelk** [comment]
In case this link is not accessible to @tawheeler

> I am failing to understand the weighting steps in Algorithm 21.9. The relevant steps are
```julia
# say w = [1,2,3]
w /= sum(w)
w = [1 - wi for wi in w]
# w would be [0.83, 0.67, 0.5] here
```

> I'm not sure if I understood this correctly, but I believe this would result in a weight vector that sums to $|S| - 1$ instead of $1$, which doesn't make sense. May I ask if there might be a typo here?

**Comment by tawheeler** [comment]
I think that is indeed a mistake. It should be:
```
dists = [<L1 distances>]
w = normalize([1/(d+eps) for d in dists], 1)
```

We can confirm with Kyle if we want to, but this is how kernel smoothing does it (section 8.3).

I'll commit a fix. Thank you!

**Comment by tawheeler** [comment]
@Tom-CCC, we typically add contributors to our acknowledgements section. If you would like to be added, could you please share your first and last name?

**Comment by mykelk** [comment]
I'll double check with Kyle real quick.

**Comment by Tom-CCS** [comment]
Sure, My name is Shengtong Zhang.

**Comment by mykelk** [comment]
Great! We're still digging into this. The reference implementation is here:
https://github.com/trey0/zmdp/blob/master/src/pomdpBounds/SawtoothUpperBound.cc#L46

**Comment by mykelk** [comment]
We have updated the implementation in Alg. 21.9 and reposted the PDF and acknowledged you. We also streamlined the text in Sec. 21.6. Thank you for bringing this to our attention!
