### ISSUE TITLE
Error in equation D.6

### ISSUE THREAD

**Issue by marketneutral** [algorithmsbooks/decisionmaking#110]
Hello, I think you have the wrong sign on the L2 penalty. The loss function is being minimized so you need to add the L2 penalty in order to incentivize smaller elements of the theta vector. In your equation you are subtracting the L2 penalty.

$$\arg\min_\theta \sum_{(x,y) \in D} \ell(f_\theta(x), y) - \beta\|| \theta \||^2$$

should be

$$\arg\min_\theta \sum_{(x,y) \in D} \ell(f_\theta(x), y) + \beta\|| \theta \||^2$$

**Comment by mykelk** [comment]
Yes! Thank you. We will correct this and acknowledge you in the errata.
