### ISSUE TITLE
Crying baby observation model mismatch

### ISSUE THREAD

**Issue by mykelk** [algorithmsbooks/decisionmaking#114]
Example 19.2 says singing to the baby yields a perfect observation (though the meaning of this might not be super precise). This seems to be inconsistent with the observation model on p. 617 which gives O(cry | sing, hungry) = 90%. (Credit to Kathryn Lesh)

**Comment by tawheeler** [comment]
Confirmed that the problem definition uses O(cry | sing, hungry) = 90%.
Updated that statement.

![2024-11-17_08-48](https://github.com/user-attachments/assets/061b9d8a-2ffe-484d-9ffa-1918e768ca55)
