### ISSUE TITLE
EPUB or MOBI support

### ISSUE THREAD

**Issue by kamlekar** [algorithmsbooks/decisionmaking#23]
Any future plans to support for EPUB or MOBI so users can read on e-readers?

Currently, we can use Calibre software but that won't compile properly because it has code but not just text.

Thanks.

**Comment by mykelk** [comment]
I started to play with Calibre to try converting, but it reflows the text and ends up turning everything into a mess. Are there conversion tools for EPUB and MOBI that preserve the formatting? I'm happy to give anything you suggest a try. I don't expect that this book (and other Tufte style books) would do very well on a small Kindle, but it would work well in a PDF viewer on a larger tablet.

**Comment by kasravi** [comment]
have you seen pop-notes for your side notes? 
from this page: [https://publisha.github.io/pages/footnotes](https://publisha.github.io/pages/footnotes/)

> The pop-up note reference is supported by Apple in their iBooks app for MACs and iOS on tablets etc. It is also documented that later Kobo devices also support pop-up notes.

> It is also supported on later models of the Kindle when an ePub is converted to the MOBI format.

> Other devices and software that cannot support pop-up notes will simply function as hyperlinks to the list of notes at the end of the chapter or section

**Comment by mykelk** [comment]
Thanks! We can explore this. The immediate focus at the moment is getting a PDF finalized so that it can go to print. I'd also want to make sure that the equations look good.

**Comment by rejuvyesh** [comment]
https://pdf2htmlex.github.io/pdf2htmlEX/ might be of interest. `epub/mobi` are just zipped html files in a way.

**Comment by quintrino** [comment]
Hoping for a this too, I generally prefer to read on an e-reader to supporting formats other than PDF would be fantastic.

**Comment by mykelk** [comment]
I was able to get the book into HTML using pdf2htmlEX on Ubuntu 20 and it looks good and preserves the formatting, equations, etc. However, converting it to EPUB / MOBI from either the PDF or HTML just results in a mess, at least using Calibre.

**Comment by AlexandrParkhomenko** [comment]
If anyone wannt the book in html formats, the formulas need convert to <mathml>, or convert to images. I have no idea why pdf is bad.
