### ISSUE TITLE
Forward Search tough to interpret

### ISSUE THREAD

**Issue by zsunberg** [algorithmsbooks/decisionmaking#42]
Hey guys, I have just spent quite some time trying to interpret the Forward Search algorithm 9.2, but it is still not quite clear to me how it is supposed to work. In particular, I don't understand the
```julia
U'(s) = forward_search(P, s, d-1, U).u
```
line. It seems like there should be an `s'` there and a for loop over states.

It might make more sense to implement it more like Alg 4.6 in the DMU book - that one is really clear.

**Comment by tawheeler** [comment]
I think the idea was to re-use `lookahead` and generally mimic the style used to make the policy gradient algorithms more compact.
I agree that this formulation has more indirection and actual implementations would not look like that.
@mykelk would you consider changing this back to what we had before?

**Comment by zsunberg** [comment]
I think it is actually not correct as written now. I think there should be a loop over all `s'` around the `U'` line. If you fix that, I think it would actually be clear.

**Comment by mykelk** [comment]
I think it's correct as it is. That `U'(s)` is just an approximation of the utility function at the next step. The loop tries out different actions and uses one-step lookahead with that utility function as the approximation in the next step. It's different from how it is normally presented, but when I taught it last quarter, this seemed to be easier for the students to understand.

**Comment by zsunberg** [comment]
Oooh, I see, that line is *defining a function*, not storing a single value
for s.

Ok, I agree it is correct. I think it would be more clear if the function
argument name was `s'`. I still think the version from DMU is a bit more
clear, but I think it is not too bad.

- Zach

**Comment by zsunberg** [comment]
To be concrete about the reason that the DMU version seems clearer - it is recursing through one function, while the new one is recursing through three (`forward_search`, `lookahead`, and `U'`), so it is a bit harder to follow imo
