### ISSUE TITLE
Algorithm 2.1 (page 26) run error

### ISSUE THREAD

**Issue by dawnjeanh** [algorithmsbooks/decisionmaking#45]
I'm grateful for a book that explains decision-making in detail, but I'm curious why the first example code in the book is wrong. I use julia 1.5.3, which version is suitable for this book?

the code is 

> ...
X = Variable(:x, 2)
Y = Variable(:y, 2)
Z = Variable(:z, 2)
φ = Factor([X, Y, Z], FactorTable(
    (x=1, y=1, z=1) => 0.08,
    (x=1, y=1, z=2) => 0.31,
    (x=1, y=2, z=1) => 0.09,
    (x=1, y=2, z=2) => 0.37,
    (x=2, y=1, z=1) => 0.01,
    (x=2, y=1, z=2) => 0.05,
    (x=2, y=2, z=1) => 0.02,
    (x=2, y=2, z=2) => 0.07,
))

The output is

> ERROR: LoadError: MethodError: Cannot `convert` an object of type NamedTuple{(:x, :y, :z),Tuple{Int64,Int64,Int64}} to an object of type Dict{Symbol,Int64}
Closest candidates are:
  convert(::Type{T}, ::T) where T<:AbstractDict at abstractdict.jl:515
  convert(::Type{T}, ::AbstractDict) where T<:AbstractDict at abstractdict.jl:517
  convert(::Type{T}, ::T) where T at essentials.jl:171
  ...
Stacktrace:
 [1] setindex!(::Dict{Dict{Symbol,Int64},Float64}, ::Float64, ::NamedTuple{(:x, :y, :z),Tuple{Int64,Int64,Int64}}) at ./dict.jl:372
 [2] Dict{Dict{Symbol,Int64},Float64}(::Pair{NamedTuple{(:x, :y, :z),Tuple{Int64,Int64,Int64}},Float64}) at ./dict.jl:107
 [3] top-level scope at /home/hanxj/code/julia/demo.jl:36
 [4] include(::Function, ::Module, ::String) at ./Base.jl:380
 [5] include(::Module, ::String) at ./Base.jl:368
 [6] exec_options(::Base.JLOptions) at ./client.jl:296
 [7] _start() at ./client.jl:506
in expression starting at /home/hanxj/code/julia/demo.jl:36

**Comment by mykelk** [comment]
You'll need to use the utility function defined in the appendix for this automatic conversion to work (see last sentence in the caption for this example):
![image](https://user-images.githubusercontent.com/6294079/107171253-2e13b400-6977-11eb-9a1a-30bf96703876.png)

**Comment by dawnjeanh** [comment]
OK, I got it. Thank you very much
