### ISSUE TITLE
typo? "admissable" instead of "admissible"

### ISSUE THREAD

**Issue by chauvinSimon** [algorithmsbooks/decisionmaking#49]
reading `9.8. labeled heuristic search 193` in [`2021-01-05 15:52:36-08:00, revision 2f3d6e6`].

The margin says:
> "8 Such a heuristic is referred to as an **admissable** heuristic."

![2021-02-10_19-06](https://user-images.githubusercontent.com/34301767/107551917-26e8e200-6bd3-11eb-9b84-b80cf7b9dc63.png)

I think it should be "admissible", as used in Exercise 9.2. for instance.

**Comment by mykelk** [comment]
Fixed. Will repost later today. Thanks!
