### ISSUE TITLE
Maximization Bias Sidenote

### ISSUE THREAD

**Issue by zsunberg** [algorithmsbooks/decisionmaking#53]
I couldn't find anything in the book about Maximization Bias. In my experience this can be a big problem for Q learning (esp. with neural networks) and has a relatively easy fix in double Q learning. There is a really good discussion in Sutton and Barto section 6.7. Could we add a sidenote and index entry about this?

**Comment by mykelk** [comment]
Great idea! I've assigned this to myself. I hope to work it in within a week.

**Comment by mykelk** [comment]
Posted!
