### ISSUE TITLE
MVNormal covariance matrix pos definite

### ISSUE THREAD

**Issue by johannes-fischer** [algorithmsbooks/decisionmaking#55]
On page 29 it states the covariance matrix of a multivariate normal distribution should be positive semidefinite. I think to not have a degenerate distribution and to use eq. (2.20) you need that it's positive definite.

**Comment by johannes-fischer** [comment]
And in the next paragraph is reads 

> If we have a multivariate Gaussian with all of the variables independent, then we can assume that the covariance matrix Σ is diagonal with only n independent parameters.

Here I would delete the words "we can assume that" to make it more clear that this is implied by independence.

**Comment by mykelk** [comment]
Good catches. I fixed both and will post later today.
