### ISSUE TITLE
Section for solutions

### ISSUE THREAD

**Issue by johannes-fischer** [algorithmsbooks/decisionmaking#56]
I think its awesome that you provide all the solutions to the exercises! Also I also like it a lot that the solutions are not packed at the end of the book, like they are in some other textbooks. However, I imagine it could be tempting for students/people who are studying the book to take a glance at the solution before intensively thinking about the exercise themselves and then easily getting the feeling "A yeah, I would have also come up with this". 
So I was wondering if it is worthwhile to add another section for the solutions in each chapter. So after section 2.8 - Exercises there would be section 2.9 - Solutions.

**Comment by mykelk** [comment]
Thank you for your feedback. In our previous book, we put the solutions at the end of the book as is customary. The overwhelming feedback from students is that they like it coming immediately after the question. They just cover the solution with a piece of paper to avoid looking it prematurely.
