### ISSUE TITLE
Example 2.3

### ISSUE THREAD

**Issue by garibaldu** [algorithmsbooks/decisionmaking#60]
At least under Julia 1.4.1, 
```ϕ = Factor([X, Y, Z], FactorTable(....)```
gives
```MethodError: Cannot `convert` an object of type NamedTuple{(:x, :y, :z),Tuple{Int64,Int64,Int64}} to an object of type Dict{Symbol,Int64}```

**Comment by mykelk** [comment]
In newer versions of the book, we have a comment in the caption: "The construction of the factor table using named tuples takes advantage of the utility functions defined in appendix G.5." Did you run that code in G.5?

**Comment by garibaldu** [comment]
Ah, that will be the problem! Thanks.
