### ISSUE TITLE
Singing

### ISSUE THREAD

**Issue by zsunberg** [algorithmsbooks/decisionmaking#61]
I interpret figure F10 to mean that singing is never optimal for the new baby problem. I found it somewhat confusing that this action is included in the problem if it should never be taken (not to mention that it is sad that we should never sing to the baby). Do you have any plans to reformulate the problem so that singing is beneficial, or take the singing out of the problem to simplify it?

Or perhaps this is a lesson that points to the disappointing fact that it is hard to find problems where expensive active information gathering is beneficial.

I think it you keep the problem the way it is, it would be nice to put a note in the caption for F10 that clearly says that singing is never optimal so that readers can be sure they are not interpreting it wrong.

**Comment by tawheeler** [comment]
Interesting, looks like that was generated using value iteration with a horizon of 10.
We know from here that singing is optimal for some beliefs for some finite horizons:
![image](https://user-images.githubusercontent.com/3334079/110728775-76bac900-81d2-11eb-95c5-2ac564f03cde.png)

So I wouldn't say it is never optimal to sing.

**Comment by zsunberg** [comment]
Ah, got it. That is interesting. I did not look at 20.3 closely enough. Might still be worth putting a note in the F10 caption explaining this.

**Comment by mykelk** [comment]
Sounds good. I can take care of this. Thanks!

**Comment by tawheeler** [comment]
@zsunberg thanks for finding this! @mykelk thanks for fixing!

**Comment by mykelk** [comment]
Fixed and reposted. Thanks!
