### ISSUE TITLE
Confusion on Example 22.2

### ISSUE THREAD

**Issue by hmray2025** [algorithmsbooks/decisionmaking#64]
Looking at example 22.2, I was confused by how the different Q values were calculated. For U_1([1.0,0.0]), I would expect this to be equal to the maximum of the dot product of the alpha vectors and the belief [max(alpha^T*b)], resulting in a value of -2. Instead it is equal to -3.2157. The other Q values in this example seem to have been calculated differently as well. Is this a bug or is there something I don't understand? 

Discussed with Dr. Zach Sunberg.

**Comment by tawheeler** [comment]
Thank you @hmray2025, the issue seems to bethat the forward search is being conducted to depth 2. Thus, U_1([1,0]) is actually running forward search with depth 1 to get an evaluation, and not directly evaluating the belief on the value function.

**Comment by tawheeler** [comment]
I'll add a note in the text to this effect.

**Comment by tawheeler** [comment]
`Each $U_1$ value must be evaluated by recursively looking ahead and eventually evaluating the approximate value function.`

**Comment by tawheeler** [comment]
We updated the sentence to: "Each U1 value is evaluated by recursing one level deeper in equation (22.1) and using the approximate value function defined for the alpha vectors for U0."
