### ISSUE TITLE
Typo: Algorithm 21.8 - cross reference

### ISSUE THREAD

**Issue by VivaldoMendes** [algorithmsbooks/decisionmaking#66]
On page 425, Algorithm 21.8 is mentioned in the text as being (algorithm 21.6).

Don´t know if already corrected.

**Comment by mykelk** [comment]
Does it look right [here](https://algorithmsbook.com/files/dm.pdf)?

**Comment by VivaldoMendes** [comment]
Yes, it does. Sorry, the crossrefs were correct. Rereading sections 21.4 and 21.5 more carefully, I can see now that there was no typo at all.
