### ISSUE TITLE
Koopman operator

### ISSUE THREAD

**Issue by owiecc** [algorithmsbooks/decisionmaking#68]
Do you plan to cover the Koopman operator, e.g. as implemented in [DiffEqUncertainty.jl](https://github.com/SciML/DiffEqUncertainty.jl) package? Here are some of the nice things this package can do: [quantifying expectations](https://tutorials.sciml.ai/html/DiffEqUncertainty/01-expectation_introduction.html) and [optimization under uncertinty](https://tutorials.sciml.ai/html/DiffEqUncertainty/02-AD_and_optimization.html).

**Comment by mykelk** [comment]
Neat! We have a chapter on uncertainty propagation in Chapter 18 of our _Algorithms for Optimization_ book that talks about efficient ways to estimating expectation, variance, etc. when propagating probability distributions through nonlinear functions. I don't think we will cover it in _Algorithms for Decision Making_, but possibly in a future book on validation.
