### ISSUE TITLE
Mutating function notation

### ISSUE THREAD

**Issue by johannes-fischer** [algorithmsbooks/decisionmaking#70]
`gibbs_sample` and `update_gibbs_sample` in algorithm 3.10 mutate the argument `a`. So maybe it would be clearer to call them `gibbs_sample!` and `update_gibbs_sample!`, according to julia convention of functions mutating their arguments.
Possibly also removing the explicit assignment `a=gibbs_sample(...)`.

**Comment by mykelk** [comment]
Fixed and reposted. Thanks!
