### ISSUE TITLE
Upper case variable

### ISSUE THREAD

**Issue by johannes-fischer** [algorithmsbooks/decisionmaking#71]
In chapter 3.8, page 60 there is one uppercase `$X_i^{(k)}$` in the second paragraph. To me it seems more consistent to make that a lower case `$x_i^{(k)}$`, since it is referring to a component of the iterate `$x_{1:n}^{(k)}$` rather than to the random variable `$X_i$` (since it has a superscript `$(k)$`). But I think it is also clearly understandable the way it is now.

**Comment by mykelk** [comment]
Fixed and reposted. Thanks!
