### ISSUE TITLE
Test programs for algorithms

### ISSUE THREAD

**Issue by general-rishkin** [algorithmsbooks/decisionmaking#72]
Many thanks for this book and teaching Algorithms for Decisions from scratch. Pedagogically excellent.

Forgive me if I am mistaken but I was looking over the book and I am wondering if there are tests one could use for the algorithms. One of the reasons I ask is because I would like to translate the code to a different programming language as I am reading. I find that the  process helps my understanding. So, having a simple program to each algorithm would be wonderful.

**Comment by mykelk** [comment]
Thank you for the kind words. We do have tests embedded in the tex source. We're focusing all of our energy on finalizing the text before it goes to print with MIT Press. Once that happens, we will work on making the code and other supporting material accessible. One thing that we will be able to release in the near term (within a couple of weeks) are the example problems described in the appendix. We will release the code in a Julia package, so you can execute them side by side with (say) a python implementation. Keep in mind that the various regression tests that we have will not always result in an exact match; many of the algorithms we discuss depend on random number generation.

**Comment by general-rishkin** [comment]
That is excellent. Looking forward to the package of example problems.
