### ISSUE TITLE
UKF algorithm (19.5)

### ISSUE THREAD

**Issue by johannes-fischer** [algorithmsbooks/decisionmaking#74]
1. The algorithm description mentions scalars `$\alpha, \beta, \kappa$` which do not appear in the algorithm.

2. Example 19.4 sounds like `sqrt(::Matrix)` cannot be used to compute a matrix square root with `A=BB'`. However, in alg 19.5 `sqrt` is used instead of the earlier mentioned Cholesky decomposition. I assume that `sqrt(A::Matrix)` returns a symmetric matrix if `A` is symmetric positive definite in which case it doesn't matter, but maybe example 19.4 should reflect this.

**Comment by tawheeler** [comment]
Hmm - not sure why the algorithm was reverted to `sqrt`. I moved it to Cholesky, fixed the caption, and added you to the acknowledgements.  Thanks!
