### ISSUE TITLE
(S, A, T, R, y) (S, A, T, R, O, Z, y) tuples

### ISSUE THREAD

**Issue by zsunberg** [algorithmsbooks/decisionmaking#75]
Given the ubiquity of the "tuple definition" of MDPs and POMDPs in the literature, I think it would be worth mentioning it directly in the text with a simple sentence like "Thus, an infinite-horizon POMDP is completely defined by the tuple (S, A, O, T, R, Z, \gamma). In julia, this can be represented with the structure in Listing XX. The `TRO` field is redundant with T, R, and O, but provides a convenient way to sample"

Of course, some or all of this might fit better in a caption, but I think mentioning the "tuple definition" is helpful - I recently sent a student to go look for it in the book and was surprised he could not find it.

**Comment by mossr** [comment]
I'd offer my support of this, and the opinion of using the \langle \rangle syntax: `⟨𝒮, 𝒜, T, R, γ⟩`

**Comment by mykelk** [comment]
Done! And posted.
