### ISSUE TITLE
Exercise 24.5

### ISSUE THREAD

**Issue by dipplestix** [algorithmsbooks/decisionmaking#78]
Choosing each uniformly at random isn't a Nash equilibrium (as player 1's best response would be to always choose dinner, increasing her utility to 1 from 2/3). 

$$\pi^1(dinner) = 2/3, \pi^1(movie) = 1/3, \pi^2 = 1-\pi^1$$ is the NE

**Comment by mykelk** [comment]
Yes, you are exactly right. We will fix this today.

**Comment by mykelk** [comment]
Kyle updated it. Can you check it out to make sure it resolves your concern?

**Comment by dipplestix** [comment]
Looks great.

Thanks for the book, really enjoyed it.
