### ISSUE TITLE
Possible typo in Appendix A.16 (pg. 564)

### ISSUE THREAD

**Issue by wjmanuel** [algorithmsbooks/decisionmaking#81]
Second Paragraph:
"If this path can be followed from node to node along the direction of the edges, then
we can call this path a _directed path_. A _directed path_ is a path without regard to the
direction of the edges."

Should the second instance of _directed path_ actually be _undirected path_?

**Comment by mykelk** [comment]
Yes! Thanks for catching that! I'll fix this and repost the entire book by the end of the month.
