### ISSUE TITLE
Typo in Ch. 22, pg. 448: "beiefs"

### ISSUE THREAD

**Issue by lkruse** [algorithmsbooks/decisionmaking#86]
The branch and bound technique originally introduced in the context of MDPs
can be extended to POMDPs. The same algorithm in section 9.4 can be used
without modification (see example 22.3), relying on the appropriate look-ahead
implementation to update **beiefs** and account for the observations. The efficiency
of the algorithm still depends on the quality of the upper and lower bounds for
pruning

**Comment by mykelk** [comment]
Thanks! Fixed!
