### ISSUE TITLE
Algorithm 7.9 use of enumerate

### ISSUE THREAD

**Issue by dylan-asmar** [algorithmsbooks/decisionmaking#87]
It appears `enumerate` is not used properly in Algorithm 7.9.

Based on the [documentation](https://docs.julialang.org/en/v1/base/iterators/#Base.Iterators.enumerate), I believe it should be
``` julia
for (i, s) in enumerate(𝒫.𝒮)
    U[i] = backup(𝒫, U, s)
end
```

**Comment by mykelk** [comment]
Fixed! Thanks!
