### ISSUE TITLE
Missing state in `π()` in equation 20.8

### ISSUE THREAD

**Issue by mossr** [algorithmsbooks/decisionmaking#89]
![image](https://user-images.githubusercontent.com/1592413/141203286-67814daf-6474-4c9e-ba12-74a0a6639e56.png)

Shouldn't the `π()` calls be `π(s)`, and why does the superscript have `π(o)` in the right-most U^{π(o)}?

Was this on purpose to save space?

**Comment by mykelk** [comment]
![image](https://user-images.githubusercontent.com/6294079/141219191-c489bbac-67a7-45fb-9cc9-c3626ae514fb.png)

**Comment by mossr** [comment]
Whoops 😬
