### ISSUE TITLE
A small question on page 115, Eq.(6.3)

### ISSUE THREAD

**Issue by jianzuo** [algorithmsbooks/decisionmaking#91]
Hello,
I have read on Chapter 6.3, Page 115, found that the Eq.(6.3) is not 
consistent with the description in the book. Shouldn't it be U(x) = \lambda x - x^2?
Since the maximum point is x=\lambda / 2.

**Comment by tawheeler** [comment]
You are right! Thank you - will be fixed in future uploads.
If you would like to share your name for the acknowledgements section, please let me know what it is.
