### ISSUE TITLE
Page 27, Example 2.4 - Equivalence of joint prob. table and tree representation

### ISSUE THREAD

**Issue by LudwigStumpp** [algorithmsbooks/decisionmaking#93]
Hello! Thanks for the lovely book!

I have a question about page 27 and the following equivalence:

![image](https://user-images.githubusercontent.com/42147848/164502976-d7d38281-ad42-43a7-8bb4-b4f600a1d44f.png)

I am wondering why the circled prob. in the tree is not assigned the value of 0.02, as this would be the sum of the two joint events of the table on the left (marginalizing over Z). Following this pattern, the sum of all leaf-nodes would then also be 1, which is what I would expect.

What am I missing?

**Comment by AlexandrParkhomenko** [comment]
Hello, LudwigStumpp.
Because this probability for each set of variables.

Suppose that we need to know probability for X=0, Y=0, Z=1
There is have a graph.

1st step. We start at X and go down the red line, because X=0.
2nd step. We continue in Y and go down the red line.
3th step.  It doesn't matter if Z is 1 or 0, we have a probability 0.01.
We get this probability for our values.

Best regards,
Alex

**Comment by LudwigStumpp** [comment]
Hi AlexandrParkhomenko,

thanks for reaching out :).

I agree to what you are saying and probably this just depends on how we interprete the tree representation, but isn't the probability of **reaching** the state you described (X=0, Y=0) equal to 0.02 (0.01 + 0.01, according to the table)?

Or are you saying that here specifically one needs to inreprete the tree as: "If I reach a leaf and I still haven't traversed a variable (Z in this case) then the probability for either event is given by the leaf number"?

Best,
Ludwig

**Comment by mykelk** [comment]
The tree represents the values for the joint probability distribution. So you can use it to evaluate P(x,y,z) for any x, y, and z. If you want to evaluate P(x,y), then you would have to marginalize out Z. You would get P(x,y) = P(x,y,z^0) + P(x,y,z^1) = 0.01 + 0.01 = 0.02. Thanks for the kind words about the book! Glad you are enjoying it.
