### ISSUE TITLE
Equation 7.22

### ISSUE THREAD

**Issue by zsunberg** [algorithmsbooks/decisionmaking#94]
I think equation 7.22 should be just

s' = T_s s + T_a a + w

instead of T(s' | s, a) = ...

If you want to talk about distributions in this case, I think it would be more consistent for the right side to have a normal distribution similar to equation 2.28.

**Comment by mykelk** [comment]
Yes, you're definitely right. We will fix this.

**Comment by mykelk** [comment]
Done and reposted. Thanks!
