### ISSUE TITLE
Missing loop code for algorithms in chapter 5 on descent methods

### ISSUE THREAD

**Issue by 00krishna** [algorithmsbooks/decisionmaking#95]
I was looking at the code in chapter 5 of the book on First-Order methods. The algorithms are 
presented in this manner:

```
abstract type DescentMethod end
struct GradientDescent <: DescentMethod
    α
end
init!(M::GradientDescent, f, ∇f, x) = M
function step!(M::GradientDescent, f, ∇f, x)
    α, g = M.α, ∇f(x)
    return x - α*g
end
```
But what seems to be missing is a sort of loop code where the `step!` function is applied in a `while` loop until a tolerance is met. I could probably figure this out myself, but it seems like this code should be in the book right? Perhaps I missed it in a different chapter, but I looked as best I could.

**Comment by mykelk** [comment]
Also, I think this was intended for Algorithms for Optimization, which is associated with this repo: https://github.com/algorithmsbooks/optimization/

**Comment by 00krishna** [comment]
Oh yes. Sorry, I did not realize I was posting to the wrong repo. Darn. But thanks for the comments. Yeah, it would really help if you also included some of the plotting code as well, so that we can replicate some of the plots. Having the plots allows users to run their own experiments. But I am sure that you are already thinking of that. Thanks again.

**Comment by 00krishna** [comment]
Here is the actual code as well. I found it in the notebooks. 

https://github.com/algorithmsbooks/algforopt-notebooks/blob/master/first-order.ipynb
