### ISSUE TITLE
Example 4.2

### ISSUE THREAD

**Issue by AlexandrParkhomenko** [algorithmsbooks/decisionmaking#98]
Hello Mykel J. Kochenderfer, Tim A. Wheeler, Kyle H. Wray !
This is full example:
```julia
using Graphs

struct Variable
    name::Symbol
    m::Int # number of possible values
end
   
G = SimpleDiGraph(3)
add_edge!(G, 1, 2)
add_edge!(G, 3, 2)
vars = [Variable(:A, 2), Variable(:B, 2), Variable(:C, 2)]
D = [1 2 2 1; 1 2 2 1; 2 2 2 2]

function prior(vars, G)
    n = length(vars)
    r = [vars[i].m for i in 1:n]
    q = [prod([r[j] for j in inneighbors(G, i)]) for i in 1:n]
    return [ones(q[i], r[i]) for i in 1:n]
end

println(prior(vars, G))
```
```bash
[[1.0 1.0], [1.0 1.0; 1.0 1.0; 1.0 1.0; 1.0 1.0], [1.0 1.0]]
```
The Algorythm produces only the Ones.
What am I doing wrong?

Best regards,
Alexandr.

**Comment by mykelk** [comment]
Yep, it should produce matrices of ones. I think Example 4.2 illustrates how this matrix of ones can be added to the data matrix to obtain the posterior Dirichlet parameters.

**Comment by AlexandrParkhomenko** [comment]
I just need to pay more attention to the text. Thanks a lot for the book, Mykel !
